debug: false


# Default sizes will work for ALL LIVING ENTITIES that spawn
# If you want certain mobs to not change in size, list them below with max and min set to 1 (their default size)
defaultmax: 1.2
defaultmin: 0.8


# List of worlds to not scale mobs in
# List all worlds where mobs should not vary in size
excluded-worlds:
  - example_world


# Mob listings if you want specific mobs to be specific sizes
# Mobs must be named as they appear in game. For example, Glow Squid is glow_squid
# To get a list of their entity names, visit https://minecraft.wiki/w/Mob
# Numbers act as percentages where 1 = default size, and 1.5 is 1 and a half times the size, and .8 is 80% the normal size
mobs:
  wither:
    max: 1
    min: 1
  cow:
    max: 1.2
    min: 0.7
  pig:
    max: 1.3
    min: 0.8