name: MobSizeRandomizer
version: '${version}'
main: com.autcraft.mobsizerandomizer.MobSizeRandomizer
api-version: '1.20'
load: STARTUP
commands:
  mobsizerandomizer:
    description: Main Command
permissions:
  mobsizerandomizer.help:
    description: Main command permission
    default: true
  mobsizerandomizer.reload:
    description: Reload the configuration
    default: op